<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CertificateSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('certificates')->upsert(
            [
                [
                    'name' => 'sertifikat_belajar dasprog_javascript',
                    'issuer' => 'Coding Camp Power by DBS Foundation',
                    'issued_at' => '2024',
                    'credential_id' => null,
                    'credential_url' => null,
                    'image' => 'assets/certificates/sertifikat_belajar_dasprog_javascript.png',
                    'file' => null,
                    'description' => null,
                    'is_active' => true,
                    'sort_order' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'certificate-DQLAB',
                    'issuer' => 'DQLAB',
                    'issued_at' => '2025',
                    'credential_id' => null,
                    'credential_url' => null,
                    'image' => 'assets/certificates/certificate-DQLAB.png',
                    'file' => null,
                    'description' => null,
                    'is_active' => true,
                    'sort_order' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'sertifikat_coding,belajar dasar pemrograman',
                    'issuer' => 'Coding Camp Power by DBS Foundation',
                    'issued_at' => '2025',
                    'credential_id' => null,
                    'credential_url' => null,
                    'image' => 'assets/certificates/sertifikat-coding.png',
                    'file' => null,
                    'description' => null,
                    'is_active' => true,
                    'sort_order' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Introduction to Financial Literacy',
                    'issuer' => 'Coding Camp Power by DBS Foundation',
                    'issued_at' => '2025',
                    'credential_id' => null,
                    'credential_url' => null,
                    'image' => 'assets/certificates/sertifikat-financial-literacy.png',
                    'file' => null,
                    'description' => null,
                    'is_active' => true,
                    'sort_order' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Database MySQL (Tingkat Dasar)',
                    'issuer' => 'PT Nimcomlab Teknologi Indonesia',
                    'issued_at' => '2025',
                    'credential_id' => null,
                    'credential_url' => null,
                    'image' => 'assets/certificates/sertifikat-mysql.png',
                    'file' => null,
                    'description' => null,
                    'is_active' => true,
                    'sort_order' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'sertifikat membuat Front End',
                    'issuer' => 'Coding Camp Power by DBS Foundation',
                    'issued_at' => '2024',
                    'credential_id' => null,
                    'credential_url' => null,
                    'image' => 'assets/certificates/sertifikat-frontend.png',
                    'file' => null,
                    'description' => null,
                    'is_active' => true,
                    'sort_order' => 6,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Sertifikat_Software Quality Assurance Basic Level',
                    'issuer' => 'PT Nimcomlab Teknologi Indonesia',
                    'issued_at' => '2026',
                    'credential_id' => null,
                    'credential_url' => null,
                    'image' => 'assets/certificates/sertifikat-sqa-basic-level.png',
                    'file' => null,
                    'description' => null,
                    'is_active' => true,
                    'sort_order' => 7,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Sertifikat Database Administrator',
                    'issuer' => 'LSP Universitas Bina Sarana Informatika',
                    'issued_at' => '2026',
                    'credential_id' => 'sertifikat Database Administator',
                    'credential_url' => null,
                    'image' => 'assets/certificates/sertifikat-database-administrator.png',
                    'file' => null,
                    'description' => 'Sertifikat kompetensi Data Management dengan skema Database Administrator yang menunjukkan kemampuan dalam pengelolaan dan pemeliharaan basis data.',
                    'is_active' => true,
                    'sort_order' => 8,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Sertifikat Sosial dan Media II',
                    'issuer' => 'UKM Kerohanian Islam UBSI Kampus Kota Tegal',
                    'issued_at' => '2026',
                    'credential_id' => '7347',
                    'credential_url' => null,
                    'image' => 'assets/certificates/sertifikat-sosial-media-ii.png',
                    'file' => null,
                    'description' => 'Sertifikat kegiatan Sosial dan Media II sebagai bagian dari aktivitas dan pengembangan pengalaman organisasi di UKM Kerohanian Islam UBSI Kampus Kota Tegal.',
                    'is_active' => true,
                    'sort_order' => 9,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ],
            ['name'],
            [
                'issuer',
                'issued_at',
                'credential_id',
                'credential_url',
                'image',
                'file',
                'description',
                'is_active',
                'sort_order',
                'updated_at',
            ]
        );
    }
}